
server:
  port: 8902

spring:
  application:
    name: StockService
  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
